# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "xilet"
email = "admin@jiyanjiyu.com"
link = "https://jiyanjiyu.com"
avatar = ""
