# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "xilet"
email = "xilet@msn.com"
link = "https://github.com/xilet"
avatar = ""
